### PR TITLE
Add file editor support

### PR DESCRIPTION
**Pull request by guidoaguiar**
Added option to edit files

### CODE REVIEW

**Comment by VoidNoi** [comment]
Oh cool I was gonna start working on this today, I'll check it out in a bit

**Comment by guidoaguiar** [comment]
Take your time, it is not perfect, but it is a start.

**Comment by VoidNoi** [comment]
I believe with these changes everything is working just as intended. There were some changes that caused horizontal navigation bugs but it should be fixed now.

**Comment by VoidNoi** [comment]
I'm done here, if you think everything is alright I'll merge it

**Pull request merged**
